[package]
name = "typetag"
version = "0.1.7"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Serde serializable and deserializable trait objects"
repository = "https://github.com/dtolnay/typetag"
documentation = "https://docs.rs/typetag"
keywords = ["serde"]
categories = ["encoding"]
readme = "README.md"
edition = "2018"

[features]
default = ["inventory"]
runtime = ["typetag-impl/runtime"]

[workspace]
members = ["impl"]

[dependencies]
cfg-if = "1.0.0"
erased-serde = "0.3"
inventory = { version = "0.1", optional = true }
lazy_static = "1.0"
serde = { version = "1.0", features = ["derive"] }
typetag-impl = { version = "=0.1.7", path = "impl" }

[dev-dependencies]
bincode = "1.0"
serde_json = "1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
